all:
  children:
    haproxy:
      hosts:
        haproxy1:
          ansible_host: 172.16.112.210
          ansible_user: vagrant
    keepalived:
      hosts:
        web1:
          ansible_host: 172.16.112.210
          ansible_user: vagrant
          keepalived_role: BACKUP
          keepalived_priority_num: 99
