# -*- mode: ruby -*-
# vi: set ft=ruby :
nodes = {
  'master01'	=> [1, 100],
  # 'worker01'  => [1, 101],
  # 'worker02'  => [1, 102],
}

Vagrant.configure("2") do |config|
  config.vm.box = "bachnc/rhel9"
  config.ssh.username = "sysadmin"
  nodes.each do |prefix, (count, ip_start)|
    count.times do |i|
      hostname = "%s" % [prefix, (i+1)]
      config.vm.define "#{hostname}" do |box|
        box.vm.hostname = "#{hostname}.book"
        box.vm.network :private_network, ip: "172.16.112.#{ip_start+i}", :netmask => "255.255.255.0"
        # VMware Fusion
        box.vm.provider :vmware_fusion do |v|
          v.ssh_info_public = true
          v.gui = true
          v.vmx["ethernet0.virtualdev"] = "vmxnet3"
          v.vmx["ethernet1.virtualdev"] = "vmxnet3"
          v.vmx['mks.enable3d'] = true                        # enable 3D acceleration
          v.vmx['vmci0.present'] = true                       # enable Virtual Machine Configuration Interface
          v.vmx['hpet0.present'] = true                       # enable High Precision Event Timer
          v.vmx['powerType.powerOff'] = 'soft'                # regular power settings
          v.vmx['powerType.powerOn'] = 'soft'                 # regular power settings
          v.vmx['powerType.suspend'] = 'soft'                 # regular power settings
          v.vmx['powerType.reset'] = 'soft'                   # regular power settings
          v.vmx['guestOS'] = 'arm-rhel9-64'                   # select 'arm-rhel9-64' as 'guostOS' in VMware
          v.vmx['numvcpus'] = '2'                             # two processor cores reserved for vm
          v.vmx['cpuid.coresPerSocket'] = '2'                 # one socket reserved for vm [1(socket)*2(CPU)=2(CPU)]
          v.vmx['vcpu.hotadd'] = true                         # enable VMware Hot Add for CPU
          v.vmx['memsize'] = '2048'                           # reserve 2GB RAM for vm
          v.vmx['mem.hotadd'] = true                          # enable VMWare Hot Add for RAM
        end
      end
    end
  end
end